apiVersion: v1
kind: Service
metadata:
  name: bda
spec:
  selector:
    app: bda
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bda
  template:
    metadata:
      labels:
        app: bda
    spec:
      containers:
        - name: app
          image: kmore23/poly_cloud_curse:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always