apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-container
  template:
    metadata:
      labels:
        app: elastic-container
    spec:
      containers:
        - name: elastic-container
          image: elasticsearch:7.9.0
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          ports:
            - containerPort: 9200
              name: rest
              protocol: TCP
            - containerPort: 9300
              name: inter-node
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
          env:
            - name: cluster.name
              value: "elastic-cluster"
            - name: xpack.security.enabled
              value: "false"
            - name: discovery.type
              value: "single-node"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: elasticsearch-pv-claim
---
# Elasticsearch PV Claim
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: elasticsearch-pv-claim
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elastic-container
spec:
  selector:
    app: elastic-container
  ports:
    - port: 9200
      targetPort: 9200
  type: LoadBalancer