---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-container
  labels:
    task: logging
    k8s-app: logstash
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  pipeline.conf: "input {
  tcp {
    port => \"5046\"
                   }
  file {
  path => \"/usr/share/data/HeadHunter_train.csv\"
  start_position => \"beginning\"
  sincedb_path => \"/dev/null\"
  }
}

  filter {
  csv {
  columns => [
  \"review_id\",
  \"city\",
  \"position\",
  \"positive\",
  \"negative\",
  \"salary_rating\",
  \"team_rating\",
  \"managment_rating\",
  \"career_rating\",
  \"workplace_rating\",
  \"rest_recovery_rating\",
  \"target\" ]
  separator => \",\"
  skip_header => true
  }
}

  output {
  stdout {

}
  elasticsearch {
  action => \"index\"
  hosts => \"elastic-container:9200\"
  index => \"train\"
  }
}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-container
spec:
  serviceName: logstash-container
  replicas: 1
  selector:
    matchLabels:
      app: logstash-container
  template:
    metadata:
      labels:
        app: logstash-container
    spec:
      containers:
        - name: logstash-container
          image: logstash:8.7.1
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          ports:
            - containerPort: 5046
              name: rest
              protocol: TCP
            - containerPort: 5047
              name: inter-node
              protocol: TCP
            volumeMounts:
              - mountPath: /config
                name: config
              - mountPath: /pipeline
                name: pipeline
      volumes:
        - name: config
          configMap:
            name: logstash-config
            items:
              - key: logstash.yml
                path: logstash.yml
        - name: pipeline
          configMap:
            name: logstash-config
            items:
              - key: pipeline.conf
                path: pipeline.conf
            env:
              - name: ELASTICSEARCH_HOSTS
                value: http://elastic-container:9200
              - name: xpack.reporting.enabled
                value: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: logging
    kubernetes.io/name: logstash
  name: logstash-container
spec:
  ports:
    - port: 5046
      targetPort: 5046
      name: lumberjack
  selector:
    k8s-app: logstash