apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      tcp {
        port => "5046"
      }
      file {
        path => "/usr/share/data/HeadHunter_train.csv"
        start_position => "beginning"
        sincedb_path => "/dev/null"
      }
    }

    filter {
      csv {
        columns => ["review_id","city","position","positive","negative","salary_rating","team_rating","managment_rating","career_rating","workplace_rating","rest_recovery_rating","target"]
        separator => ","
        skip_header => true
      }
    }

    output {
      stdout {

      }
      elasticsearch {
        action => "index"
        hosts => "elastic-container:9200"
        index => "train"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elastic-container:9200"
            - name: xpack.reporting.enabled
              value: "true"
          image: logstash:7.17.4
          ports:
            - containerPort: 5046
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/logstash/config
            - name: logstash-pipeline-volume
              mountPath: /usr/share/logstash/pipeline
            - name: data
              mountPath: /usr/share/data
          resources:
            limits:
              memory: "1Gi"
              cpu: "2500m"
            requests:
              memory: "1Gi"
              cpu: "800m"
      volumes:
        - name: config-volume
          configMap:
            name: logstash-configmap
            items:
              - key: logstash.yml
                path: logstash.yml
        - name: logstash-pipeline-volume
          configMap:
            name: logstash-configmap
            items:
              - key: logstash.conf
                path: logstash.conf
        - name: data
          persistentVolumeClaim:
            claimName: elasticsearch-pv-claim
---
# Elasticsearch PV Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: Service
apiVersion: v1
metadata:
  name: logstash-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    app: logstash
  ports:
    - protocol: TCP
      port: 5046
      targetPort: 5046
  type: LoadBalancer